---
title: "Reproducible Pitch Presentation"
author: "Koray KIRKAR"
date: "12/30/2020"
output:
  slidy_presentation: default
always_allow_html: yes
---

## Introduction

You will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

## Shiny Application

-Write a shiny application with associated supporting documentation. 

-The documentation should be thought of as whatever a user will need to get started using your application.

-Deploy the application on Rstudio's shiny server

-Share the application link by pasting it into the provided text box

-Share your server.R and ui.R code on github

## The application must include the following:

-Some form of input (widget: textbox, radio button, checkbox, ...) 

-Some operation on the ui input in sever.R

-Some reactive output displayed as a result of server calculations

-You must also include enough documentation so that a novice user could use your application.

-The documentation should be at the Shiny website itself. Do not post to an external link.

## R Code 

```
shinyUI(fluidPage(
    titlePanel("Covid-19 Dashboard"),
    sidebarLayout(
        sidebarPanel(
            selectInput(
                "country", 
                label    = "Country", 
                multiple = TRUE, 
                choices  = unique(covid19()$administrative_area_level_1), 
                selected = "Turkey"
            ),
            selectInput(
                "type", 
                label    = "type", 
                choices  = c("confirmed", "tests", "recovered", "deaths")
            ),
```

## R Code (continued)

```
selectInput(
                "level", 
                label    = "Granularity", 
                choices  = c("Country" = 1, "Region" = 2, "City" = 3), 
                selected = 2
            ),
            dateRangeInput(
                "date", 
                label    = "Date", 
                start    = "2020-01-01"
            ),
        ),
        
        mainPanel(
            h3("Visualization Covid-19"),
            plotlyOutput("covid19plot")
        )
    )
)
```

## Thanks

Check the GitHUb Repository for this project.

[GitHUb Repo](https://github.com/kkirkar/shiny/)